name: PR Audit

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  editorconfig:
    runs-on: ubuntu-latest
    steps:

    - name: CheckoutCode
      uses: actions/checkout@v2

    - name: EditorConfig-Action
      uses: FarzamMohammadi/EditorConfig-Action@master
      env:
        # Only lint files changed in pull request
        ALWAYS_LINT_ALL_FILES: false
        # Automatic error fixing not yet supported by EditorConfig-Action
        # Forced off to avoid unintentionally enabling when upgrading to new version
        C_FIX_ERROR: false
